# PROBLEM NAME
PROBLEM_NAME = 'Adult recensement'

# CSV VARIABLES
CSV_PATH = "data/adult.data"
CSV_COLUMNS = [0, 4, 12]
CSV_TRUTH = -1

# EGM VARIABLES
ELBOW_MAX_RANGE = 18

# PCA VARIABLES
PCA_DIM = 3

# K-MEANS VARIABLES
ITERATIONS = 15
CLUSTERS = 5
COLORS = ['red', 'blue', 'green', 'cyan', 'magenta', 'yellow']
COLORS2 = ['red', 'green', 'blue']
ITEM_SIZE = 5
CENTROID_SIZE = 100

# GRAPH VARIABLES
# CAMERA
PLT_ANGLE = 20  # 15
PLT_AZIM = 125  # 110
PLT_ZOOM = 0.005  # 0.005

# DIMENSIONS
DIM1_NAME = 'dim 1'
DIM2_NAME = 'dim 2'
DIM3_NAME = 'dim 3'
